### ISSUE TITLE
starting hwmon service

### ISSUE THREAD

**Issue by esm** [openbmc/phosphor-hwmon#18]
when I try to start my hwmon service running the command systemctl start xyz.openbmc_project.Hwmon@.service , I get the error Failed to start xyz.openbmc_project.Hwmon@.service: Unit namexyz.openbmc_project.Hwmon@.service is missing the instance name. How do I get or know the instance name of my service?

**Comment by spinler** [comment]
Since that service file has a @ in the name, it is a template service and needs a string in between the '@' and '.' when started.

**Comment by esm** [comment]
thanks
